"""Add canonical_status severity canonical_flags to signals

Revision ID: 157371e0464b
Revises: 006
Create Date: 2026-02-06 13:23:21.469226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '157371e0464b'
down_revision: Union[str, Sequence[str], None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'audit_events',
        existing_comment='Append-only audit trail. UPDATE/DELETE blocked by trigger.',
        schema=None
    )
    op.drop_table_comment(
        'decisions',
        existing_comment='Immutable record of decisions. UPDATE/DELETE blocked by trigger.',
        schema=None
    )
    op.drop_table_comment(
        'evidence_packs',
        existing_comment='Immutable evidence bundles. UPDATE/DELETE blocked by trigger.',
        schema=None
    )
    # Create enum type first
    canonical_status_enum = postgresql.ENUM('breach', 'observation', name='canonical_status', create_type=False)
    canonical_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('signals', sa.Column('canonical_status', sa.Enum('breach', 'observation', name='canonical_status', create_type=False), nullable=True))
    op.add_column('signals', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('signals', sa.Column('canonical_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_signals_content_hash', table_name='signals')
    op.create_index(op.f('ix_signals_content_hash'), 'signals', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_content_hash'), table_name='signals')
    op.create_index('idx_signals_content_hash', 'signals', ['content_hash'], unique=False)
    op.drop_column('signals', 'canonical_flags')
    op.drop_column('signals', 'severity')
    op.drop_column('signals', 'canonical_status')
    # Drop enum type
    canonical_status_enum = postgresql.ENUM('breach', 'observation', name='canonical_status', create_type=False)
    canonical_status_enum.drop(op.get_bind(), checkfirst=True)
    op.create_table_comment(
        'evidence_packs',
        'Immutable evidence bundles. UPDATE/DELETE blocked by trigger.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'decisions',
        'Immutable record of decisions. UPDATE/DELETE blocked by trigger.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'audit_events',
        'Append-only audit trail. UPDATE/DELETE blocked by trigger.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
