"""Add replay_namespace column

Revision ID: 9f66600c3e18
Revises: 001
Create Date: 2026-01-13 23:40:19.396003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f66600c3e18'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('replay_namespace', sa.String(length=100), nullable=True))
    op.alter_column('audit_events', 'aggregate_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_events', 'actor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_audit_events_occurred_at', table_name='audit_events')
    op.drop_index('idx_audit_events_aggregate', table_name='audit_events')
    op.create_index('idx_audit_events_aggregate', 'audit_events', ['aggregate_type', 'aggregate_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_events_type', 'audit_events', ['event_type', 'occurred_at'], unique=False)
    op.drop_index('idx_decisions_decided_at', table_name='decisions')
    op.create_index('idx_decisions_exception', 'decisions', ['exception_id'], unique=False)
    op.create_index('idx_decisions_timestamp', 'decisions', ['decided_at'], unique=False)
    op.create_foreign_key(None, 'decisions', 'evidence_packs', ['evidence_pack_id'], ['id'])
    op.add_column('evaluations', sa.Column('replay_namespace', sa.String(length=100), nullable=True))
    op.drop_index('idx_evaluations_input_hash', table_name='evaluations')
    op.create_index('idx_evaluations_hash', 'evaluations', ['input_hash'], unique=False)
    op.create_index('idx_evaluations_policy', 'evaluations', ['policy_version_id', 'evaluated_at'], unique=False)
    op.create_index('idx_evidence_packs_decision', 'evidence_packs', ['decision_id'], unique=False)
    op.drop_index('idx_exceptions_status', table_name='exceptions')
    op.create_index('idx_exceptions_status', 'exceptions', ['status', 'severity', 'raised_at'], unique=False)
    op.create_index('idx_exceptions_fingerprint', 'exceptions', ['fingerprint', 'resolved_at'], unique=False)
    op.alter_column('policies', 'pack',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('idx_policies_pack', table_name='policies')
    op.create_unique_constraint('uq_policy_name_pack', 'policies', ['name', 'pack'])
    op.drop_index('idx_policy_versions_valid', table_name='policy_versions')
    op.drop_constraint('uq_policy_version', 'policy_versions', type_='unique')
    op.create_unique_constraint('uq_policy_version_number', 'policy_versions', ['policy_id', 'version_number'])
    op.drop_constraint('policy_versions_policy_id_fkey', 'policy_versions', type_='foreignkey')
    op.create_foreign_key(None, 'policy_versions', 'policies', ['policy_id'], ['id'])
    op.alter_column('signals', 'pack',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('idx_signals_observed_at', table_name='signals')
    op.drop_index('idx_signals_pack_type', table_name='signals')
    op.create_index('idx_signals_ingested', 'signals', ['ingested_at'], unique=False)
    op.create_index('idx_signals_type_time', 'signals', ['pack', 'signal_type', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signals_type_time', table_name='signals')
    op.drop_index('idx_signals_ingested', table_name='signals')
    op.create_index('idx_signals_pack_type', 'signals', ['pack', 'signal_type'], unique=False)
    op.create_index('idx_signals_observed_at', 'signals', ['observed_at'], unique=False)
    op.alter_column('signals', 'pack',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'policy_versions', type_='foreignkey')
    op.create_foreign_key('policy_versions_policy_id_fkey', 'policy_versions', 'policies', ['policy_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_policy_version_number', 'policy_versions', type_='unique')
    op.create_unique_constraint('uq_policy_version', 'policy_versions', ['policy_id', 'version_number'])
    op.create_index('idx_policy_versions_valid', 'policy_versions', ['valid_from', 'valid_to'], unique=False)
    op.drop_constraint('uq_policy_name_pack', 'policies', type_='unique')
    op.create_index('idx_policies_pack', 'policies', ['pack'], unique=False)
    op.alter_column('policies', 'pack',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index('idx_exceptions_fingerprint', table_name='exceptions')
    op.drop_index('idx_exceptions_status', table_name='exceptions')
    op.create_index('idx_exceptions_status', 'exceptions', ['status'], unique=False)
    op.drop_index('idx_evidence_packs_decision', table_name='evidence_packs')
    op.drop_index('idx_evaluations_policy', table_name='evaluations')
    op.drop_index('idx_evaluations_hash', table_name='evaluations')
    op.create_index('idx_evaluations_input_hash', 'evaluations', ['input_hash'], unique=False)
    op.drop_column('evaluations', 'replay_namespace')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_index('idx_decisions_timestamp', table_name='decisions')
    op.drop_index('idx_decisions_exception', table_name='decisions')
    op.create_index('idx_decisions_decided_at', 'decisions', ['decided_at'], unique=False)
    op.drop_index('idx_audit_events_type', table_name='audit_events')
    op.drop_index('idx_audit_events_aggregate', table_name='audit_events')
    op.create_index('idx_audit_events_aggregate', 'audit_events', ['aggregate_id'], unique=False)
    op.create_index('idx_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.alter_column('audit_events', 'actor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('audit_events', 'aggregate_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('audit_events', 'replay_namespace')
    # ### end Alembic commands ###
